import Image from "next/image";
import Link from "next/link";
import { Header } from "@/components/layout/header";
import { formatPrice } from "@/data/products";
import { AddToCartButton } from "@/components/cart/add-to-cart-button";
import { getProductBySlug } from "@/services/product.service";
import { notFound } from "next/navigation";
import { WishlistButton } from "@/components/product/wishlist-button";
import type { Metadata } from "next";
import { siteConfig } from "@/data/site";

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const product = await getProductBySlug(slug); if (!product) return { title: "Product not found" }; return { title: product.name, description: product.description, alternates: { canonical: `/product/${product.slug ?? slug}` }, openGraph: { title: product.name, description: product.description, images: product.image ? [{ url: product.image, alt: product.name }] : undefined } }; }

export default async function ProductPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const product = await getProductBySlug(slug); if (!product) notFound(); const jsonLd = { "@context": "https://schema.org", "@type": "Product", name: product.name, description: product.description, image: product.images ?? [product.image], offers: { "@type": "Offer", priceCurrency: product.currency, price: product.price, availability: product.stockStatus === "out-of-stock" ? "https://schema.org/OutOfStock" : "https://schema.org/InStock", url: `${siteConfig.url}/product/${product.slug ?? slug}` } }; return <main className="min-h-screen bg-[#f9fcff] px-6 pb-20 pt-36 sm:px-10"><Header /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><div className="mx-auto grid max-w-[1100px] gap-12 lg:grid-cols-2"><div className="relative min-h-[500px] overflow-hidden rounded-2xl bg-white"><Image src={product.image} alt={product.name} fill className="object-cover" unoptimized /></div><div className="self-center"><p className="text-xs font-semibold uppercase tracking-wide text-[#3051a0]">{product.category}</p><h1 className="mt-4 text-5xl font-medium">{product.name}</h1><p className="mt-5 text-2xl font-semibold">{formatPrice(product.price)}</p><p className="mt-6 leading-7 text-[#334f6d]">{product.description}</p>{product.stockStatus === "out-of-stock" && <p className="mt-5 font-medium text-red-700">Currently out of stock</p>}<div className="mt-8 flex flex-wrap items-center gap-3">{product.stockStatus !== "out-of-stock" && <AddToCartButton product={product} />}<WishlistButton product={product} compact={false} /></div><Link href="/shop" className="mt-5 inline-block text-sm font-semibold text-[#3051a0]">Back to shop</Link></div></div></main>; }
